version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "matmult"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nf4acv45ce32"
s3_prefix = "matmult"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
